// try{
//     let x = undefined;
//     console.log(x[0]);
// }catch(err){
//     console.log("Error Handling is catch",err);
// }finally{
//     console.log("finally always get executed")
// }

// console.log("end")


try{
    console.log("Hello")
    console.log(a);

}catch(err){
    console.log("handle",err)
}finally{
    console.log("Alaways run doesnt matter code have error or not")
}                 

console.log("end")